if a new mail address is added to an existing contact, nil is unexpectedly found (#37)
Fatal error: Unexpectedly found nil while unwrapping an Optional value